version: '3'
name: 'todo'

networks:
  main:
    driver: bridge

services:

  todo:
    container_name: todo
    build:
      context: .
      dockerfile: docker/todo/Dockerfile
    restart: always
    depends_on:
      - auth
      - redis
      - postgres
    networks:
      - main
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    restart: always
    depends_on:
      - postgres
    networks:
      - main
    env_file:
      - .env
    
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    networks:
      - main
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - ./database:/var/lib/postgresql/data
  
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - main
    ports:
      - 6379:6379